### ISSUE TITLE
All things item script related.

### ISSUE THREAD

**Issue by RamonNZ** [AngelArenaAllstars/oaa#103]
The item script directory is in /Scripts/vscripts/

So the questions are what to name the script directory and the naming convention for item lua script files.

Angel Arena Reborn for example calls the directory /items/
and the files just the name e.g. "aegis.lua"
Angel Arena Black Star also the directory /items/ 
and the files the word item then the name of the item e.g. item_aegis.lua
Epic Boss Fight uses the directory /lua_item/
and the files without the word item e.g. aegis.lua

I'd like to suggest the directory name /itemscripts/ just so nobody will get confused with the /items/ folder in /NPC/. 
For the script file name perhaps item_aegis.lua, or script_aegis.lua or even script_item_aegis.lua

Throwing in the word script in the directory and/or lua file means less potential confusion by people looking for the item files.

**Comment by chrisinajar** [comment]
`scripts\vscripts\itemscripts\` is quite redundant.

`scripts\vscripts\items\item_aegis.lua` seems less redundant
`scripts\vscripts\items\aegis.lua` seems reasonable

`scripts\vscripts\items\radiance\radiance_2.lua`
`scripts\vscripts\items\radiance\frozen_radiance.lua` seems well organized

I'm less worried about confusion since the file extensions are different and they're in different folders. Most people on the team use sublime text, which does fuzzy matching, so matching by those filenames you were putting in would actually result in the right file every time (`scriptitemskadi` or `scitsklua` as i would probably type it)

**Comment by Chronophylos** [comment]
I hate the `scripts/vscripts` repetition.
And `scripts\vscripts\items\item_aegis.lua` or even `scripts\vscripts\itemscripts\item_aegis.lua`  is totally unnecessary.

Organization is key:
`scripts\vscripts\items\radiance\radiance_2.lua`
`scripts\vscripts\items\radiance\frozen_radiance.lua`
Both look good but I'd do:
`scripts\vscripts\items\radiance\level_2.lua`
`scripts\vscripts\items\radiance\frozen.lua`
as this gives more information by looking at it.

**Comment by RamonNZ** [comment]
The second thing is that I just wanted to mention that with item scripts, from what I have tested so far, is that with item coding, you can use either the default item ability, e.g. "Baseclass" "item_blink", in which case you won't be able to edit much about it except small things, and you _can't add any abilities_ to it. The other option is "baseclass" "item_datadriven", in which case you have to write the item data and script from the ground up.

What this also means in effect, is that because the base class scripts are hard coded, some abilities aren't actually able to be reproduced quite as they are in the game.

**Comment by RamonNZ** [comment]
removing item_ from the name makes sense, 

I do dislike having an extra directory after \items\, but for the reason that it is different to the items folder in the \npc\ directory, so figuring out what the script name (which includes putting the directory) in the item takes more thought and could lead to scripts not firing if it gets too confusing.

I definitely would not change the name of the item script completely from the item e.g. level_2.lua. That would drive a scripter balmy, and actually cause lots of errors just by being so difficult to figure out each different name, and directory for each script. Bad idea scripting wise. 

You have to consider simple logic in the naming or it becomes harder and harder to connect the script to the items.

So I guess 
\items\radiance\radiance_2.lua 
will have to do, though for reasons of writing the script into the item files 
\items\radiance_2.lua 
would be easier.

**Comment by RamonNZ** [comment]
One other little thing I'm going to mention about item scripts for anybody who is going to try to write them:

From what I have tested so far with item scripting, you can use either the default item ability, e.g. "Baseclass" "item_blink", in which case you won't be able to edit much about it except small things, and you **_can't add any abilities_** to it. The other option is "baseclass" "item_datadriven", in which case you have to write the item data and script **_from the ground up._**

What this also means in effect, is that because the base class scripts are hard coded, **some abilities aren't actually able to be reproduced** quite as they are in the game due to limitations in the lua functionality.

**Comment by zelding** [comment]
I'm not sure you can do that; [Moddota](http://moddota.com/forums/discussion/4/datadriven-items) argues, if you don't match up the items and recipes names, than the shop wont draw lines in build tree. so the names has to be `item_something` and `item_recipe_something`

**Comment by RamonNZ** [comment]
zelding, I'll test that hypothesis now.

**Comment by zelding** [comment]
@RamonNZ that is possible ;)

**Comment by Chronophylos** [comment]
So it is
`scripts\vscripts\items\radiance_2.lua`
`scripts\vscripts\items\radiance_frozen.lua` ?

**Comment by RamonNZ** [comment]
That would be easiest.

**Comment by Trildar** [comment]
@RamonNZ You forgot "BaseClass" "item_lua", which from what I know, has slightly more flexibility as pretty much any ability method can be overridden or something like that. It's also possibly more organized as pretty much everything other than values will go into a Lua file.

Also, even though this issue is technically about item scripts, I have a related question about ability script organization. Should we do it like the Spell Library with `scripts/vscripts/heroes/hero_furion/force_of_nature.lua` or something more like `scripts/vscripts/abilities/furion_force_of_nature.lua`?

**Comment by Chronophylos** [comment]
I'd use `scripts/vscripts/abilities/force_of_nature.lua` because theoretically two heros could have the same ability.

**Comment by RamonNZ** [comment]
@Trildar Thanks for the information. I'd never seen that before. I'm studying up item_lua now.
